# Data Manipulation Studio

For this studio, we will revisit the data set from our last studio. If you recall, California farmers were looking for advice on growing pumpkins. We will use the same pumpkins dataset as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the dataset folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

A terminal market is a central site, often in a metropolitan area, that serves as an assembly and trading place for commodities. Terminal markets for agricultural commodities are usually at or near major transportation hubs. Definition Source

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [33]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import numpy as np
baltimore = pd.read_csv(r"C:\Users\LC Harrison Sand\OneDrive\Documents\LaunchCode\data-analysis-projects\data-manipulation\studio\data-manipulation-studio\dataset\baltimore_9-24-2016_9-30-2017.csv")
boston = pd.read_csv(r"C:\Users\LC Harrison Sand\OneDrive\Documents\LaunchCode\data-analysis-projects\data-manipulation\studio\data-manipulation-studio\dataset\boston_9-24-2016_9-30-2017.csv")
new_york = pd.read_csv(r"C:\Users\LC Harrison Sand\OneDrive\Documents\LaunchCode\data-analysis-projects\data-manipulation\studio\data-manipulation-studio\dataset\new-york_9-24-2016_9-30-2017.csv")
philly = pd.read_csv(r"C:\Users\LC Harrison Sand\OneDrive\Documents\LaunchCode\data-analysis-projects\data-manipulation\studio\data-manipulation-studio\dataset\philadelphia_9-24-2016_9-30-2017.csv")

## Clean Your Data

    "In the last lesson, we cleaned the data related to San Francisco. Pull up your notebook from the last lesson and use it as a reference to clean up these new dataframes."

In [34]:
print("Baltimore")
for col in baltimore.columns:
    pct_missing = np.mean(baltimore[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
    
print("----------------------------------------------------------------------------------------")
print("Boston")
for col in boston.columns:
    pct_missing = np.mean(boston[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

print("----------------------------------------------------------------------------------------")
print("New York")
for col in new_york.columns:
    pct_missing = np.mean(new_york[col].isnull())
   
    print('{} - {}%'.format(col, round(pct_missing*100)))
print("----------------------------------------------------------------------------------------")
print("Philly")
for col in philly.columns:
    pct_missing = np.mean(philly[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))



for data in [baltimore, boston, new_york, philly]:
    data["Type"] = data["Type"].fillna("Conventional")
    data["Variety"] = data["Variety"].fillna("Other")
    data = data.drop(["Trans Mode", "Grade", "Environment" "Crop", "Storage", "Condition", "Quality", "Unit of Sale", "Origin District", "Environment"], axis=1)

Baltimore
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 1%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 3%
Origin District - 100%
Item Size - 16%
Color - 80%
Environment - 100%
Unit of Sale - 84%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
----------------------------------------------------------------------------------------
Boston
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 92%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 81%
Item Size - 1%
Color - 14%
Environment - 100%
Unit of Sale - 87%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
----------------------------------------------------------------------------------------
New York
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 84%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 87%
Item Size - 7%
Color - 81%
Environment - 100%
Unit of Sale - 78%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%
----------------------------------------------------------------------------------------
Philly
Commodity Name - 0%
City Name - 0%
Type - 100%
Package - 0%
Variety - 0%
Sub Variety - 79%
Grade - 100%
Date - 0%
Low Price - 0%
High Price - 0%
Mostly Low - 0%
Mostly High - 0%
Origin - 0%
Origin District - 100%
Item Size - 21%
Color - 100%
Environment - 100%
Unit of Sale - 81%
Quality - 100%
Condition - 100%
Appearance - 100%
Storage - 100%
Crop - 100%
Repack - 0%
Trans Mode - 100%

KeyError: "['EnvironmentCrop'] not found in axis"

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [35]:
# Combine the four dataframes into one!
northeast = pd.concat([baltimore, boston, new_york, philly], ignore_index= True)
northeast

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,BALTIMORE,Conventional,24 inch bins,Other,NaN,NaN,04/29/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
1,PUMPKINS,BALTIMORE,Conventional,24 inch bins,Other,NaN,NaN,05/06/2017,270,280.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN
2,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,160,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,NaN,NaN,11/05/2016,90,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
669,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,11/05/2016,16,18.0,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
670,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,08/26/2017,18,20.0,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
671,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/16/2017,16,16.0,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
672,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/23/2017,15,16.0,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN
673,PUMPKINS,PHILADELPHIA,NaN,1/2 bushel cartons,MINIATURE,FLAT TYPE,NaN,09/30/2017,15,18.0,...,NaN,NaN,SHELLACKED,NaN,NaN,NaN,NaN,NaN,N,NaN

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1    "1. What is the mean low and high prices for each type of **unit of sale** in the Northeast region?",
    "2. For each region, what is the average number of pumpkins per variety that came into terminal markets for the year? "

In [36]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
prices = ["Low Price", "High Price"]
mean_prices = northeast[prices].agg("mean")
print("NorthEast Prices:")
mean_prices

NorthEast Prices:

Low Price     134.183976
High Price    150.671365
dtype: float64

In [42]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
varieties = northeast.groupby("Variety").nunique()
varieties

,Commodity Name,City Name,Type,Package,Sub Variety,Grade,Date,Low Price,High Price,Mostly Low,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
Variety,,,,,,,,,,,,,,,,,,,,,
BIG MACK TYPE,1,3,1,3,0,0,11,6,7,9,...,2,0,2,0,0,0,0,0,1,0
BLUE TYPE,1,1,0,1,0,0,7,1,1,1,...,1,0,0,0,0,0,0,0,1,0
CINDERELLA,1,2,1,2,0,0,18,11,10,11,...,2,0,0,0,0,0,0,0,2,0
FAIRYTALE,1,2,1,2,0,0,10,8,8,8,...,2,0,0,0,0,0,0,0,1,0
HOWDEN TYPE,1,4,1,2,0,0,11,12,14,20,...,1,0,1,0,0,0,0,0,1,0
HOWDEN WHITE TYPE,1,1,1,1,0,0,2,2,1,2,...,0,0,0,0,0,0,0,0,1,0
KNUCKLE HEAD,1,3,0,2,0,0,7,3,3,3,...,1,0,0,0,0,0,0,0,1,0
MINIATURE,1,4,1,3,2,0,12,7,7,7,...,2,0,1,0,0,0,0,0,1,0
MIXED HEIRLOOM VARIETIES,1,2,1,1,0,0,4,3,2,3,...,0,0,0,0,0,0,0,0,1,0
Other,1,1,1,1,0,0,2,1,1,1,...,0,0,0,0,0,0,0,0,1,0
PIE TYPE,1,4,1,5,0,0,18,24,27,26,...,2,0,1,0,0,0,0,0,1,0

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!